### ISSUE TITLE
Error al generar el PDF417

### ISSUE THREAD

**Issue by DSGroup2016** [dansanti/l10n_cl_stock_picking#3]
Estimado al momento de validar la guía de despacho y las boletas en el punto de venta me da el siguiente error

Traceback (most recent call last):
  File "/opt/odoo/openerp/http.py", line 648, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/openerp/http.py", line 685, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/openerp/http.py", line 321, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/openerp/http.py", line 314, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/openerp/http.py", line 964, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/openerp/http.py", line 514, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 888, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/addons/web/controllers/main.py", line 880, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/addons/point_of_sale/point_of_sale.py", line 821, in create_from_ui
    order_id = self._process_order(cr, uid, order, context=context)
  File "/opt/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 354, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/custom/addons/l10n_cl_dte_point_of_sale/models/point_of_sale.py", line 876, in _process_order
    order_id._timbrar()
  File "/opt/custom/addons/l10n_cl_dte_point_of_sale/models/point_of_sale.py", line 1330, in _timbrar
    dte['Documento ID'] = self._dte()
  File "/opt/custom/addons/l10n_cl_dte_point_of_sale/models/point_of_sale.py", line 1301, in _dte
    dte['TEDd'] = self.get_barcode(invoice_lines['no_product'])
  File "/opt/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/custom/addons/l10n_cl_dte_point_of_sale/models/point_of_sale.py", line 1206, in get_barcode
    image.save(barcodefile,'PNG')
  File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 1650, in save
    self.load()
  File "/usr/local/lib/python2.7/dist-packages/PIL/EpsImagePlugin.py", line 336, in load
    self.im = Ghostscript(self.tile, self.size, self.fp, scale)
  File "/usr/local/lib/python2.7/dist-packages/PIL/EpsImagePlugin.py", line 143, in Ghostscript
    stdout=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No existe el archivo o el directorio

El problema al parecer lo da al momento de generar el PDF. 

Saludos y muchas gracias

**Comment by dansanti** [comment]
hola!


en ciertos vps hay algun algún tipo de restricción, se debe canabiar la
librería elaphe por pdf417gen, en l10n_cl_dte está la forma, ahora en la
mañana no puedo hacer commit, ya sería para la tarde

El 29/03/2017 23:25, "DSGroup2016" <notifications@github.com> escribió:

Estimado al momento de validar la guía de despacho me da el siguiente error

Traceback (most recent call last):
File "/opt/odoo/openerp/http.py", line 648, in _handle_exception
return super(JsonRequest, self)._handle_exception(exception)
File "/opt/odoo/openerp/http.py", line 685, in dispatch
result = self._call_function(**self.params)
File "/opt/odoo/openerp/http.py", line 321, in _call_function
return checked_call(self.db, *args, **kwargs)
File "/opt/odoo/openerp/service/model.py", line 118, in wrapper
return f(dbname, *args, **kwargs)
File "/opt/odoo/openerp/http.py", line 314, in checked_call
result = self.endpoint(*a, **kw)
File "/opt/odoo/openerp/http.py", line 964, in *call*
return self.method(*args, **kw)
File "/opt/odoo/openerp/http.py", line 514, in response_wrap
response = f(*args, **kw)
File "/opt/odoo/addons/web/controllers/main.py", line 888, in call_kw
return self._call_kw(model, method, args, kwargs)
File "/opt/odoo/addons/web/controllers/main.py", line 880, in _call_kw
return getattr(request.registry.get(model), method)(request.cr,
request.uid, *args, **kwargs)
File "/opt/odoo/openerp/api.py", line 250, in wrapper
return old_api(self, *args, **kwargs)
File "/opt/odoo/addons/point_of_sale/point_of_sale.py", line 821, in
create_from_ui
order_id = self._process_order(cr, uid, order, context=context)
File "/opt/odoo/openerp/api.py", line 250, in wrapper
return old_api(self, *args, **kwargs)
File "/opt/odoo/openerp/api.py", line 354, in old_api
result = method(recs, *args, **kwargs)
File "/opt/custom/addons/l10n_cl_dte_point_of_sale/models/point_of_sale.py",
line 876, in _process_order
order_id._timbrar()
File "/opt/custom/addons/l10n_cl_dte_point_of_sale/models/point_of_sale.py",
line 1330, in _timbrar
dte['Documento ID'] = self._dte()
File "/opt/custom/addons/l10n_cl_dte_point_of_sale/models/point_of_sale.py",
line 1301, in _dte
dte['TEDd'] = self.get_barcode(invoice_lines['no_product'])
File "/opt/odoo/openerp/api.py", line 248, in wrapper
return new_api(self, *args, **kwargs)
File "/opt/custom/addons/l10n_cl_dte_point_of_sale/models/point_of_sale.py",
line 1206, in get_barcode
image.save(barcodefile,'PNG')
File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 1650, in
save
self.load()
File "/usr/local/lib/python2.7/dist-packages/PIL/EpsImagePlugin.py", line
336, in load
self.im = Ghostscript(self.tile, self.size, self.fp, scale)
File "/usr/local/lib/python2.7/dist-packages/PIL/EpsImagePlugin.py", line
143, in Ghostscript
stdout=subprocess.PIPE)
File "/usr/lib/python2.7/subprocess.py", line 710, in *init*
errread, errwrite)
File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
raise child_exception
OSError: [Errno 2] No existe el archivo o el directorio

El problema al parecer lo da al momento de generar el PDF.

Saludos y muchas gracias

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/dansanti/l10n_cl_stock_picking/issues/3>, or mute the
thread

**Comment by dansanti** [comment]
El cambio debe ser aplicado en point of sale y stock picking.


Sobre stock picking desde pos creo hay un asunto que arreglé y no he hecho
commit, puede que aparezca error o resultados no esperados ( como pérdida
del valor monetario)

**Comment by dansanti** [comment]
closed via https://github.com/dansanti/l10n_cl_stock_picking/commit/6cce43dd34ac4271c5fc3602fa2f9884235c7047
